workspace(name = "io_bazel_rules_dotnet")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load(
    "//dotnet:defs.bzl",
    "DEFAULT_DOTNET_CORE_FRAMEWORK",
    "DOTNET_CORE_FRAMEWORKS",
    "DOTNET_NET_FRAMEWORKS",
    "core_register_sdk",
    "dotnet_nuget_new",
    "dotnet_register_toolchains",
    "dotnet_repositories",
    "mono_register_sdk",
    "net_gac4",
    "net_register_sdk",
    "nuget_package",
    "vs2017_ref_net",
)

dotnet_repositories()

dotnet_register_toolchains()

mono_register_sdk()

[net_register_sdk(
    framework,
) for framework in DOTNET_NET_FRAMEWORKS]

[core_register_sdk(
    framework,
) for framework in DOTNET_CORE_FRAMEWORKS]

# Default core_sdk
core_register_sdk(
    DEFAULT_DOTNET_CORE_FRAMEWORK,
    name = "core_sdk",
)

# Default net_sdk
net_register_sdk(
    "net471",
    name = "net_sdk",
)

net_gac4(
    name = "System.ComponentModel.DataAnnotations",
    token = "31bf3856ad364e35",
    version = "4.0.0.0",
)

[http_archive(
    name = "{}_xunit_abstractions".format(framework),
    build_file = "@io_bazel_rules_dotnet//3rd_party:abstractions.xunit/repo_{}.bzl".format(framework),
    sha256 = "302dfe0b87993528b2e0c227b4aca4bec82ed136163d7b4b3f75f24f9d43f6fa",
    strip_prefix = "abstractions.xunit-2.0.1",
    urls = ["https://github.com/xunit/abstractions.xunit/archive/2.0.1.tar.gz"],
) for framework in DOTNET_CORE_FRAMEWORKS]

[http_archive(
    name = "{}_xunit_assert".format(framework),
    build_file = "@io_bazel_rules_dotnet//3rd_party:assert.xunit/repo_{}.bzl".format(framework),
    sha256 = "82e662c9a30b9468640d4e1b0db3fca58c22d5ac6f9b7ab8cc16ba1e35515d1c",
    strip_prefix = "assert.xunit-2.4.1",
    urls = ["https://github.com/xunit/assert.xunit/archive/2.4.1.tar.gz"],
) for framework in DOTNET_CORE_FRAMEWORKS]

[http_archive(
    name = "{}_testfx".format(framework),
    build_file = "@io_bazel_rules_dotnet//3rd_party:testfx/repo_{}.bzl".format(framework),
    strip_prefix = "testfx-1.4.0",
    urls = ["https://github.com/Microsoft/testfx/archive/1.4.0.tar.gz"],
) for framework in DOTNET_CORE_FRAMEWORKS]

[http_archive(
    name = "{}_xunit".format(framework),
    build_file = "//3rd_party:xunit/repo_{}.bzl".format(framework),
    sha256 = "01a73e2fd8675fb2237ba067f2f3f12baf6d388216145fcb8374d6085f056f71",
    strip_prefix = "xunit-2.4.1",
    urls = ["https://github.com/xunit/xunit/archive/2.4.1.tar.gz"],
) for framework in DOTNET_CORE_FRAMEWORKS]

http_archive(
    name = "xunit",
    build_file = "//3rd_party:xunit/repo_{}.bzl".format(DEFAULT_DOTNET_CORE_FRAMEWORK),
    sha256 = "01a73e2fd8675fb2237ba067f2f3f12baf6d388216145fcb8374d6085f056f71",
    strip_prefix = "xunit-2.4.1",
    urls = ["https://github.com/xunit/xunit/archive/2.4.1.tar.gz"],
)

http_archive(
    name = "xunit_assert",
    build_file = "@io_bazel_rules_dotnet//3rd_party:assert.xunit/repo_{}.bzl".format(DEFAULT_DOTNET_CORE_FRAMEWORK),
    sha256 = "82e662c9a30b9468640d4e1b0db3fca58c22d5ac6f9b7ab8cc16ba1e35515d1c",
    strip_prefix = "assert.xunit-2.4.1",
    urls = ["https://github.com/xunit/assert.xunit/archive/2.4.1.tar.gz"],
)

# The rule is left as an example. It is commented out, because our CI server doesn't have VS2017 installed
# vs2017_ref_net(name = "vs2017_ref")

load("@io_bazel_rules_dotnet//tests:bazel_tests.bzl", "test_environment")

test_environment()

### Generated by the tool
nuget_package(
    name = "xunit.abstractions",
    core_files = {
        "netcoreapp2.0": [
            "lib/netstandard2.0/xunit.abstractions.dll",
            "lib/netstandard2.0/xunit.abstractions.xml",
        ],
        "netcoreapp2.1": [
            "lib/netstandard2.0/xunit.abstractions.dll",
            "lib/netstandard2.0/xunit.abstractions.xml",
        ],
    },
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/xunit.abstractions.dll",
        "netcoreapp2.1": "lib/netstandard2.0/xunit.abstractions.dll",
    },
    mono_files = [
        "lib/net35/xunit.abstractions.dll",
        "lib/net35/xunit.abstractions.xml",
    ],
    mono_lib = "lib/net35/xunit.abstractions.dll",
    net_files = {
        "net45": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net451": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net452": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net46": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net461": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net462": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net47": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net471": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "net472": [
            "lib/net35/xunit.abstractions.dll",
            "lib/net35/xunit.abstractions.xml",
        ],
        "netstandard1.0": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard1.1": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard1.2": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard1.3": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard1.4": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard1.5": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard1.6": [
            "lib/netstandard1.0/xunit.abstractions.dll",
            "lib/netstandard1.0/xunit.abstractions.xml",
        ],
        "netstandard2.0": [
            "lib/netstandard2.0/xunit.abstractions.dll",
            "lib/netstandard2.0/xunit.abstractions.xml",
        ],
    },
    net_lib = {
        "net45": "lib/net35/xunit.abstractions.dll",
        "net451": "lib/net35/xunit.abstractions.dll",
        "net452": "lib/net35/xunit.abstractions.dll",
        "net46": "lib/net35/xunit.abstractions.dll",
        "net461": "lib/net35/xunit.abstractions.dll",
        "net462": "lib/net35/xunit.abstractions.dll",
        "net47": "lib/net35/xunit.abstractions.dll",
        "net471": "lib/net35/xunit.abstractions.dll",
        "net472": "lib/net35/xunit.abstractions.dll",
        "netstandard1.0": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard1.1": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard1.2": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard1.3": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard1.4": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard1.5": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard1.6": "lib/netstandard1.0/xunit.abstractions.dll",
        "netstandard2.0": "lib/netstandard2.0/xunit.abstractions.dll",
    },
    package = "xunit.abstractions",
    version = "2.0.3",
)

nuget_package(
    name = "xunit.analyzers",
    core_files = {
        "netcoreapp2.0": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netcoreapp2.1": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
    },
    core_lib = {
        "netcoreapp2.0": "",
        "netcoreapp2.1": "",
    },
    mono_files = [
        "tools/install.ps1",
        "tools/uninstall.ps1",
    ],
    net_files = {
        "net45": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net451": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net452": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net46": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net461": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net462": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net47": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net471": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "net472": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.0": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.1": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.2": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.3": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.4": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.5": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard1.6": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
        "netstandard2.0": [
            "tools/install.ps1",
            "tools/uninstall.ps1",
        ],
    },
    net_lib = {
        "net45": "",
        "net451": "",
        "net452": "",
        "net46": "",
        "net461": "",
        "net462": "",
        "net47": "",
        "net471": "",
        "net472": "",
        "netstandard1.0": "",
        "netstandard1.1": "",
        "netstandard1.2": "",
        "netstandard1.3": "",
        "netstandard1.4": "",
        "netstandard1.5": "",
        "netstandard1.6": "",
        "netstandard2.0": "",
    },
    package = "xunit.analyzers",
    version = "0.10.0",
)

nuget_package(
    name = "xunit.assert",
    core_files = {
        "netcoreapp2.0": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netcoreapp2.1": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
    },
    core_lib = {
        "netcoreapp2.0": "lib/netstandard1.1/xunit.assert.dll",
        "netcoreapp2.1": "lib/netstandard1.1/xunit.assert.dll",
    },
    mono_files = [
        "lib/netstandard1.1/xunit.assert.dll",
        "lib/netstandard1.1/xunit.assert.xml",
    ],
    mono_lib = "lib/netstandard1.1/xunit.assert.dll",
    net_files = {
        "net45": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net451": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net452": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net46": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net461": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net462": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net47": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net471": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "net472": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard1.1": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard1.2": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard1.3": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard1.4": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard1.5": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard1.6": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
        "netstandard2.0": [
            "lib/netstandard1.1/xunit.assert.dll",
            "lib/netstandard1.1/xunit.assert.xml",
        ],
    },
    net_lib = {
        "net45": "lib/netstandard1.1/xunit.assert.dll",
        "net451": "lib/netstandard1.1/xunit.assert.dll",
        "net452": "lib/netstandard1.1/xunit.assert.dll",
        "net46": "lib/netstandard1.1/xunit.assert.dll",
        "net461": "lib/netstandard1.1/xunit.assert.dll",
        "net462": "lib/netstandard1.1/xunit.assert.dll",
        "net47": "lib/netstandard1.1/xunit.assert.dll",
        "net471": "lib/netstandard1.1/xunit.assert.dll",
        "net472": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard1.1": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard1.2": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard1.3": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard1.4": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard1.5": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard1.6": "lib/netstandard1.1/xunit.assert.dll",
        "netstandard2.0": "lib/netstandard1.1/xunit.assert.dll",
    },
    package = "xunit.assert",
    version = "2.4.1",
)

nuget_package(
    name = "xunit.extensibility.core",
    core_deps = {
        "net45": [
            "@xunit.abstractions//:net45_net",
        ],
        "net451": [
            "@xunit.abstractions//:net451_net",
        ],
        "net452": [
            "@xunit.abstractions//:net452_net",
        ],
        "net46": [
            "@xunit.abstractions//:net46_net",
        ],
        "net461": [
            "@xunit.abstractions//:net461_net",
        ],
        "net462": [
            "@xunit.abstractions//:net462_net",
        ],
        "net47": [
            "@xunit.abstractions//:net47_net",
        ],
        "net471": [
            "@xunit.abstractions//:net471_net",
        ],
        "net472": [
            "@xunit.abstractions//:net472_net",
        ],
        "netstandard1.1": [
            "@xunit.abstractions//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.abstractions//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.abstractions//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.abstractions//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.abstractions//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.abstractions//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.abstractions//:netstandard2.0_net",
        ],
    },
    core_files = {
        "netcoreapp2.0": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netcoreapp2.1": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
    },
    core_lib = {
        "netcoreapp2.0": "lib/netstandard1.1/xunit.core.dll",
        "netcoreapp2.1": "lib/netstandard1.1/xunit.core.dll",
    },
    mono_deps = [
        "@xunit.abstractions//:mono",
    ],
    mono_files = [
        "lib/net452/xunit.core.dll",
        "lib/net452/xunit.core.dll.tdnet",
        "lib/net452/xunit.core.xml",
        "lib/net452/xunit.runner.tdnet.dll",
        "lib/net452/xunit.runner.utility.net452.dll",
    ],
    mono_lib = "lib/net452/xunit.core.dll",
    net_deps = {
        "net45": [
            "@xunit.abstractions//:net45_net",
        ],
        "net451": [
            "@xunit.abstractions//:net451_net",
        ],
        "net452": [
            "@xunit.abstractions//:net452_net",
        ],
        "net46": [
            "@xunit.abstractions//:net46_net",
        ],
        "net461": [
            "@xunit.abstractions//:net461_net",
        ],
        "net462": [
            "@xunit.abstractions//:net462_net",
        ],
        "net47": [
            "@xunit.abstractions//:net47_net",
        ],
        "net471": [
            "@xunit.abstractions//:net471_net",
        ],
        "net472": [
            "@xunit.abstractions//:net472_net",
        ],
        "netstandard1.1": [
            "@xunit.abstractions//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.abstractions//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.abstractions//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.abstractions//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.abstractions//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.abstractions//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.abstractions//:netstandard2.0_net",
        ],
    },
    net_files = {
        "net45": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "net451": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "net452": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "net46": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "net461": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "net462": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "net47": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "net471": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "net472": [
            "lib/net452/xunit.core.dll",
            "lib/net452/xunit.core.dll.tdnet",
            "lib/net452/xunit.core.xml",
            "lib/net452/xunit.runner.tdnet.dll",
            "lib/net452/xunit.runner.utility.net452.dll",
        ],
        "netstandard1.1": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netstandard1.2": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netstandard1.3": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netstandard1.4": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netstandard1.5": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netstandard1.6": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
        "netstandard2.0": [
            "lib/netstandard1.1/xunit.core.dll",
            "lib/netstandard1.1/xunit.core.xml",
        ],
    },
    net_lib = {
        "net45": "lib/netstandard1.1/xunit.core.dll",
        "net451": "lib/netstandard1.1/xunit.core.dll",
        "net452": "lib/net452/xunit.core.dll",
        "net46": "lib/net452/xunit.core.dll",
        "net461": "lib/net452/xunit.core.dll",
        "net462": "lib/net452/xunit.core.dll",
        "net47": "lib/net452/xunit.core.dll",
        "net471": "lib/net452/xunit.core.dll",
        "net472": "lib/net452/xunit.core.dll",
        "netstandard1.1": "lib/netstandard1.1/xunit.core.dll",
        "netstandard1.2": "lib/netstandard1.1/xunit.core.dll",
        "netstandard1.3": "lib/netstandard1.1/xunit.core.dll",
        "netstandard1.4": "lib/netstandard1.1/xunit.core.dll",
        "netstandard1.5": "lib/netstandard1.1/xunit.core.dll",
        "netstandard1.6": "lib/netstandard1.1/xunit.core.dll",
        "netstandard2.0": "lib/netstandard1.1/xunit.core.dll",
    },
    package = "xunit.extensibility.core",
    version = "2.4.1",
)

nuget_package(
    name = "xunit.extensibility.execution",
    core_deps = {
        "net45": [
            "@xunit.extensibility.core//:net45_net",
        ],
        "net451": [
            "@xunit.extensibility.core//:net451_net",
        ],
        "net452": [
            "@xunit.extensibility.core//:net452_net",
        ],
        "net46": [
            "@xunit.extensibility.core//:net46_net",
        ],
        "net461": [
            "@xunit.extensibility.core//:net461_net",
        ],
        "net462": [
            "@xunit.extensibility.core//:net462_net",
        ],
        "net47": [
            "@xunit.extensibility.core//:net47_net",
        ],
        "net471": [
            "@xunit.extensibility.core//:net471_net",
        ],
        "net472": [
            "@xunit.extensibility.core//:net472_net",
        ],
        "netstandard1.1": [
            "@xunit.extensibility.core//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.extensibility.core//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.extensibility.core//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.extensibility.core//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.extensibility.core//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.extensibility.core//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.extensibility.core//:netstandard2.0_net",
        ],
    },
    core_files = {
        "netcoreapp2.0": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netcoreapp2.1": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
    },
    core_lib = {
        "netcoreapp2.0": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netcoreapp2.1": "lib/netstandard1.1/xunit.execution.dotnet.dll",
    },
    mono_deps = [
        "@xunit.extensibility.core//:mono",
    ],
    mono_files = [
        "lib/net452/xunit.execution.desktop.dll",
        "lib/net452/xunit.execution.desktop.xml",
    ],
    mono_lib = "lib/net452/xunit.execution.desktop.dll",
    net_deps = {
        "net45": [
            "@xunit.extensibility.core//:net45_net",
        ],
        "net451": [
            "@xunit.extensibility.core//:net451_net",
        ],
        "net452": [
            "@xunit.extensibility.core//:net452_net",
        ],
        "net46": [
            "@xunit.extensibility.core//:net46_net",
        ],
        "net461": [
            "@xunit.extensibility.core//:net461_net",
        ],
        "net462": [
            "@xunit.extensibility.core//:net462_net",
        ],
        "net47": [
            "@xunit.extensibility.core//:net47_net",
        ],
        "net471": [
            "@xunit.extensibility.core//:net471_net",
        ],
        "net472": [
            "@xunit.extensibility.core//:net472_net",
        ],
        "netstandard1.1": [
            "@xunit.extensibility.core//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.extensibility.core//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.extensibility.core//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.extensibility.core//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.extensibility.core//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.extensibility.core//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.extensibility.core//:netstandard2.0_net",
        ],
    },
    net_files = {
        "net45": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "net451": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "net452": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "net46": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "net461": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "net462": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "net47": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "net471": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "net472": [
            "lib/net452/xunit.execution.desktop.dll",
            "lib/net452/xunit.execution.desktop.xml",
        ],
        "netstandard1.1": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netstandard1.2": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netstandard1.3": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netstandard1.4": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netstandard1.5": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netstandard1.6": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
        "netstandard2.0": [
            "lib/netstandard1.1/xunit.execution.dotnet.dll",
            "lib/netstandard1.1/xunit.execution.dotnet.xml",
        ],
    },
    net_lib = {
        "net45": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "net451": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "net452": "lib/net452/xunit.execution.desktop.dll",
        "net46": "lib/net452/xunit.execution.desktop.dll",
        "net461": "lib/net452/xunit.execution.desktop.dll",
        "net462": "lib/net452/xunit.execution.desktop.dll",
        "net47": "lib/net452/xunit.execution.desktop.dll",
        "net471": "lib/net452/xunit.execution.desktop.dll",
        "net472": "lib/net452/xunit.execution.desktop.dll",
        "netstandard1.1": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netstandard1.2": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netstandard1.3": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netstandard1.4": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netstandard1.5": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netstandard1.6": "lib/netstandard1.1/xunit.execution.dotnet.dll",
        "netstandard2.0": "lib/netstandard1.1/xunit.execution.dotnet.dll",
    },
    package = "xunit.extensibility.execution",
    version = "2.4.1",
)

nuget_package(
    name = "xunit.core",
    core_deps = {
        "net45": [
            "@xunit.extensibility.core//:net45_net",
            "@xunit.extensibility.execution//:net45_net",
        ],
        "net451": [
            "@xunit.extensibility.core//:net451_net",
            "@xunit.extensibility.execution//:net451_net",
        ],
        "net452": [
            "@xunit.extensibility.core//:net452_net",
            "@xunit.extensibility.execution//:net452_net",
        ],
        "net46": [
            "@xunit.extensibility.core//:net46_net",
            "@xunit.extensibility.execution//:net46_net",
        ],
        "net461": [
            "@xunit.extensibility.core//:net461_net",
            "@xunit.extensibility.execution//:net461_net",
        ],
        "net462": [
            "@xunit.extensibility.core//:net462_net",
            "@xunit.extensibility.execution//:net462_net",
        ],
        "net47": [
            "@xunit.extensibility.core//:net47_net",
            "@xunit.extensibility.execution//:net47_net",
        ],
        "net471": [
            "@xunit.extensibility.core//:net471_net",
            "@xunit.extensibility.execution//:net471_net",
        ],
        "net472": [
            "@xunit.extensibility.core//:net472_net",
            "@xunit.extensibility.execution//:net472_net",
        ],
        "netstandard1.0": [
            "@xunit.extensibility.core//:netstandard1.0_net",
            "@xunit.extensibility.execution//:netstandard1.0_net",
        ],
        "netstandard1.1": [
            "@xunit.extensibility.core//:netstandard1.1_net",
            "@xunit.extensibility.execution//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.extensibility.core//:netstandard1.2_net",
            "@xunit.extensibility.execution//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.extensibility.core//:netstandard1.3_net",
            "@xunit.extensibility.execution//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.extensibility.core//:netstandard1.4_net",
            "@xunit.extensibility.execution//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.extensibility.core//:netstandard1.5_net",
            "@xunit.extensibility.execution//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.extensibility.core//:netstandard1.6_net",
            "@xunit.extensibility.execution//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.extensibility.core//:netstandard2.0_net",
            "@xunit.extensibility.execution//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@xunit.extensibility.core//:mono",
        "@xunit.extensibility.execution//:mono",
    ],
    net_deps = {
        "net45": [
            "@xunit.extensibility.core//:net45_net",
            "@xunit.extensibility.execution//:net45_net",
        ],
        "net451": [
            "@xunit.extensibility.core//:net451_net",
            "@xunit.extensibility.execution//:net451_net",
        ],
        "net452": [
            "@xunit.extensibility.core//:net452_net",
            "@xunit.extensibility.execution//:net452_net",
        ],
        "net46": [
            "@xunit.extensibility.core//:net46_net",
            "@xunit.extensibility.execution//:net46_net",
        ],
        "net461": [
            "@xunit.extensibility.core//:net461_net",
            "@xunit.extensibility.execution//:net461_net",
        ],
        "net462": [
            "@xunit.extensibility.core//:net462_net",
            "@xunit.extensibility.execution//:net462_net",
        ],
        "net47": [
            "@xunit.extensibility.core//:net47_net",
            "@xunit.extensibility.execution//:net47_net",
        ],
        "net471": [
            "@xunit.extensibility.core//:net471_net",
            "@xunit.extensibility.execution//:net471_net",
        ],
        "net472": [
            "@xunit.extensibility.core//:net472_net",
            "@xunit.extensibility.execution//:net472_net",
        ],
        "netstandard1.0": [
            "@xunit.extensibility.core//:netstandard1.0_net",
            "@xunit.extensibility.execution//:netstandard1.0_net",
        ],
        "netstandard1.1": [
            "@xunit.extensibility.core//:netstandard1.1_net",
            "@xunit.extensibility.execution//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.extensibility.core//:netstandard1.2_net",
            "@xunit.extensibility.execution//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.extensibility.core//:netstandard1.3_net",
            "@xunit.extensibility.execution//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.extensibility.core//:netstandard1.4_net",
            "@xunit.extensibility.execution//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.extensibility.core//:netstandard1.5_net",
            "@xunit.extensibility.execution//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.extensibility.core//:netstandard1.6_net",
            "@xunit.extensibility.execution//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.extensibility.core//:netstandard2.0_net",
            "@xunit.extensibility.execution//:netstandard2.0_net",
        ],
    },
    package = "xunit.core",
    version = "2.4.1",
)

nuget_package(
    name = "xunit",
    core_deps = {
        "net45": [
            "@xunit.core//:net45_net",
            "@xunit.assert//:net45_net",
            "@xunit.analyzers//:net45_net",
        ],
        "net451": [
            "@xunit.core//:net451_net",
            "@xunit.assert//:net451_net",
            "@xunit.analyzers//:net451_net",
        ],
        "net452": [
            "@xunit.core//:net452_net",
            "@xunit.assert//:net452_net",
            "@xunit.analyzers//:net452_net",
        ],
        "net46": [
            "@xunit.core//:net46_net",
            "@xunit.assert//:net46_net",
            "@xunit.analyzers//:net46_net",
        ],
        "net461": [
            "@xunit.core//:net461_net",
            "@xunit.assert//:net461_net",
            "@xunit.analyzers//:net461_net",
        ],
        "net462": [
            "@xunit.core//:net462_net",
            "@xunit.assert//:net462_net",
            "@xunit.analyzers//:net462_net",
        ],
        "net47": [
            "@xunit.core//:net47_net",
            "@xunit.assert//:net47_net",
            "@xunit.analyzers//:net47_net",
        ],
        "net471": [
            "@xunit.core//:net471_net",
            "@xunit.assert//:net471_net",
            "@xunit.analyzers//:net471_net",
        ],
        "net472": [
            "@xunit.core//:net472_net",
            "@xunit.assert//:net472_net",
            "@xunit.analyzers//:net472_net",
        ],
        "netstandard1.0": [
            "@xunit.core//:netstandard1.0_net",
            "@xunit.assert//:netstandard1.0_net",
            "@xunit.analyzers//:netstandard1.0_net",
        ],
        "netstandard1.1": [
            "@xunit.core//:netstandard1.1_net",
            "@xunit.assert//:netstandard1.1_net",
            "@xunit.analyzers//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.core//:netstandard1.2_net",
            "@xunit.assert//:netstandard1.2_net",
            "@xunit.analyzers//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.core//:netstandard1.3_net",
            "@xunit.assert//:netstandard1.3_net",
            "@xunit.analyzers//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.core//:netstandard1.4_net",
            "@xunit.assert//:netstandard1.4_net",
            "@xunit.analyzers//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.core//:netstandard1.5_net",
            "@xunit.assert//:netstandard1.5_net",
            "@xunit.analyzers//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.core//:netstandard1.6_net",
            "@xunit.assert//:netstandard1.6_net",
            "@xunit.analyzers//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.core//:netstandard2.0_net",
            "@xunit.assert//:netstandard2.0_net",
            "@xunit.analyzers//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@xunit.core//:mono",
        "@xunit.assert//:mono",
        "@xunit.analyzers//:mono",
    ],
    net_deps = {
        "net45": [
            "@xunit.core//:net45_net",
            "@xunit.assert//:net45_net",
            "@xunit.analyzers//:net45_net",
        ],
        "net451": [
            "@xunit.core//:net451_net",
            "@xunit.assert//:net451_net",
            "@xunit.analyzers//:net451_net",
        ],
        "net452": [
            "@xunit.core//:net452_net",
            "@xunit.assert//:net452_net",
            "@xunit.analyzers//:net452_net",
        ],
        "net46": [
            "@xunit.core//:net46_net",
            "@xunit.assert//:net46_net",
            "@xunit.analyzers//:net46_net",
        ],
        "net461": [
            "@xunit.core//:net461_net",
            "@xunit.assert//:net461_net",
            "@xunit.analyzers//:net461_net",
        ],
        "net462": [
            "@xunit.core//:net462_net",
            "@xunit.assert//:net462_net",
            "@xunit.analyzers//:net462_net",
        ],
        "net47": [
            "@xunit.core//:net47_net",
            "@xunit.assert//:net47_net",
            "@xunit.analyzers//:net47_net",
        ],
        "net471": [
            "@xunit.core//:net471_net",
            "@xunit.assert//:net471_net",
            "@xunit.analyzers//:net471_net",
        ],
        "net472": [
            "@xunit.core//:net472_net",
            "@xunit.assert//:net472_net",
            "@xunit.analyzers//:net472_net",
        ],
        "netstandard1.0": [
            "@xunit.core//:netstandard1.0_net",
            "@xunit.assert//:netstandard1.0_net",
            "@xunit.analyzers//:netstandard1.0_net",
        ],
        "netstandard1.1": [
            "@xunit.core//:netstandard1.1_net",
            "@xunit.assert//:netstandard1.1_net",
            "@xunit.analyzers//:netstandard1.1_net",
        ],
        "netstandard1.2": [
            "@xunit.core//:netstandard1.2_net",
            "@xunit.assert//:netstandard1.2_net",
            "@xunit.analyzers//:netstandard1.2_net",
        ],
        "netstandard1.3": [
            "@xunit.core//:netstandard1.3_net",
            "@xunit.assert//:netstandard1.3_net",
            "@xunit.analyzers//:netstandard1.3_net",
        ],
        "netstandard1.4": [
            "@xunit.core//:netstandard1.4_net",
            "@xunit.assert//:netstandard1.4_net",
            "@xunit.analyzers//:netstandard1.4_net",
        ],
        "netstandard1.5": [
            "@xunit.core//:netstandard1.5_net",
            "@xunit.assert//:netstandard1.5_net",
            "@xunit.analyzers//:netstandard1.5_net",
        ],
        "netstandard1.6": [
            "@xunit.core//:netstandard1.6_net",
            "@xunit.assert//:netstandard1.6_net",
            "@xunit.analyzers//:netstandard1.6_net",
        ],
        "netstandard2.0": [
            "@xunit.core//:netstandard2.0_net",
            "@xunit.assert//:netstandard2.0_net",
            "@xunit.analyzers//:netstandard2.0_net",
        ],
    },
    package = "xunit",
    version = "2.4.1",
)

nuget_package(
    name = "xunit.runner.console",
    core_files = {
        "netcoreapp2.0": [
            "tools/netcoreapp2.0/xunit.abstractions.dll",
            "tools/netcoreapp2.0/xunit.console.deps.json",
            "tools/netcoreapp2.0/xunit.console.dll",
            "tools/netcoreapp2.0/xunit.console.dll.config",
            "tools/netcoreapp2.0/xunit.console.runtimeconfig.json",
            "tools/netcoreapp2.0/xunit.runner.reporters.netcoreapp10.dll",
            "tools/netcoreapp2.0/xunit.runner.utility.netcoreapp10.dll",
            "tools/netcoreapp2.0/xunit.runner.utility.netcoreapp10.xml",
        ],
        "netcoreapp2.1": [
            "tools/netcoreapp2.0/xunit.abstractions.dll",
            "tools/netcoreapp2.0/xunit.console.deps.json",
            "tools/netcoreapp2.0/xunit.console.dll",
            "tools/netcoreapp2.0/xunit.console.dll.config",
            "tools/netcoreapp2.0/xunit.console.runtimeconfig.json",
            "tools/netcoreapp2.0/xunit.runner.reporters.netcoreapp10.dll",
            "tools/netcoreapp2.0/xunit.runner.utility.netcoreapp10.dll",
            "tools/netcoreapp2.0/xunit.runner.utility.netcoreapp10.xml",
        ],
    },
    core_lib = {
        "netcoreapp2.0": "tools/netcoreapp2.0/xunit.abstractions.dll",
        "netcoreapp2.1": "tools/netcoreapp2.0/xunit.abstractions.dll",
    },
    core_tool = {
        "net452": "tools/net452/xunit.abstractions.dll",
        "net46": "tools/net46/xunit.abstractions.dll",
        "net461": "tools/net461/xunit.abstractions.dll",
        "net462": "tools/net462/xunit.abstractions.dll",
        "net47": "tools/net47/xunit.abstractions.dll",
        "net471": "tools/net471/xunit.abstractions.dll",
        "net472": "tools/net472/xunit.abstractions.dll",
    },
    mono_files = [
        "tools/net472/xunit.abstractions.dll",
        "tools/net472/xunit.console.exe",
        "tools/net472/xunit.console.exe.config",
        "tools/net472/xunit.console.x86.exe",
        "tools/net472/xunit.console.x86.exe.config",
        "tools/net472/xunit.runner.reporters.net452.dll",
        "tools/net472/xunit.runner.utility.net452.dll",
    ],
    mono_lib = "tools/net472/xunit.abstractions.dll",
    mono_tool = "tools/net472/xunit.abstractions.dll",
    net_files = {
        "net452": [
            "tools/net452/xunit.abstractions.dll",
            "tools/net452/xunit.console.exe",
            "tools/net452/xunit.console.exe.config",
            "tools/net452/xunit.console.x86.exe",
            "tools/net452/xunit.console.x86.exe.config",
            "tools/net452/xunit.runner.reporters.net452.dll",
            "tools/net452/xunit.runner.utility.net452.dll",
        ],
        "net46": [
            "tools/net46/xunit.abstractions.dll",
            "tools/net46/xunit.console.exe",
            "tools/net46/xunit.console.exe.config",
            "tools/net46/xunit.console.x86.exe",
            "tools/net46/xunit.console.x86.exe.config",
            "tools/net46/xunit.runner.reporters.net452.dll",
            "tools/net46/xunit.runner.utility.net452.dll",
        ],
        "net461": [
            "tools/net461/xunit.abstractions.dll",
            "tools/net461/xunit.console.exe",
            "tools/net461/xunit.console.exe.config",
            "tools/net461/xunit.console.x86.exe",
            "tools/net461/xunit.console.x86.exe.config",
            "tools/net461/xunit.runner.reporters.net452.dll",
            "tools/net461/xunit.runner.utility.net452.dll",
        ],
        "net462": [
            "tools/net462/xunit.abstractions.dll",
            "tools/net462/xunit.console.exe",
            "tools/net462/xunit.console.exe.config",
            "tools/net462/xunit.console.x86.exe",
            "tools/net462/xunit.console.x86.exe.config",
            "tools/net462/xunit.runner.reporters.net452.dll",
            "tools/net462/xunit.runner.utility.net452.dll",
        ],
        "net47": [
            "tools/net47/xunit.abstractions.dll",
            "tools/net47/xunit.console.exe",
            "tools/net47/xunit.console.exe.config",
            "tools/net47/xunit.console.x86.exe",
            "tools/net47/xunit.console.x86.exe.config",
            "tools/net47/xunit.runner.reporters.net452.dll",
            "tools/net47/xunit.runner.utility.net452.dll",
        ],
        "net471": [
            "tools/net471/xunit.abstractions.dll",
            "tools/net471/xunit.console.exe",
            "tools/net471/xunit.console.exe.config",
            "tools/net471/xunit.console.x86.exe",
            "tools/net471/xunit.console.x86.exe.config",
            "tools/net471/xunit.runner.reporters.net452.dll",
            "tools/net471/xunit.runner.utility.net452.dll",
        ],
        "net472": [
            "tools/net472/xunit.abstractions.dll",
            "tools/net472/xunit.console.exe",
            "tools/net472/xunit.console.exe.config",
            "tools/net472/xunit.console.x86.exe",
            "tools/net472/xunit.console.x86.exe.config",
            "tools/net472/xunit.runner.reporters.net452.dll",
            "tools/net472/xunit.runner.utility.net452.dll",
        ],
    },
    net_lib = {
        "net452": "tools/net452/xunit.abstractions.dll",
        "net46": "tools/net46/xunit.abstractions.dll",
        "net461": "tools/net461/xunit.abstractions.dll",
        "net462": "tools/net462/xunit.abstractions.dll",
        "net47": "tools/net47/xunit.abstractions.dll",
        "net471": "tools/net471/xunit.abstractions.dll",
        "net472": "tools/net472/xunit.abstractions.dll",
    },
    net_tool = {
        "net452": "tools/net452/xunit.abstractions.dll",
        "net46": "tools/net46/xunit.abstractions.dll",
        "net461": "tools/net461/xunit.abstractions.dll",
        "net462": "tools/net462/xunit.abstractions.dll",
        "net47": "tools/net47/xunit.abstractions.dll",
        "net471": "tools/net471/xunit.abstractions.dll",
        "net472": "tools/net472/xunit.abstractions.dll",
    },
    package = "xunit.runner.console",
    version = "2.4.1",
)
### End of generated by the tool
