"Generated"

load("//dotnet/private/packs/targeting:targeting_pack.bzl", "targeting_pack")

def targeting_packs():
    """Targeting packs"""

    targeting_pack(name = "microsoft.netframework.referenceassemblies.v1.0.3", packs = ["@dotnet.packs//microsoft.netframework.referenceassemblies.v1.0.3"])
    targeting_pack(name = "netstandard.library.v2.0.3", packs = ["@dotnet.packs//netstandard.library.v2.0.3"])
    targeting_pack(name = "netstandard.library.ref.v2.1.0", packs = ["@dotnet.packs//netstandard.library.ref.v2.1.0"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.0-rc2-3002702", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.0-rc2-3002702"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.0"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.1", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.1"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.3", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.3"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.4", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.4"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.5-servicing-004880-00", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.5-servicing-004880-00"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.5", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.5"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.7", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.7"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.8", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.8"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.9", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.9"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.10", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.10"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.11", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.11"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.12", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.12"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.13", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.13"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.14", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.14"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.15", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.15"])
    targeting_pack(name = "microsoft.netcore.app.v1.0.16", packs = ["@dotnet.packs//microsoft.netcore.app.v1.0.16"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.0-preview1-001100-00", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.0-preview1-001100-00"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.0", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.0"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.1", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.1"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.2", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.2"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.4", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.4"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.5", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.5"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.6", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.6"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.7", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.7"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.8", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.8"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.9", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.9"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.10", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.10"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.11", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.11"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.12", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.12"])
    targeting_pack(name = "microsoft.netcore.app.v1.1.13", packs = ["@dotnet.packs//microsoft.netcore.app.v1.1.13"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.0-preview1-002111-00", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.0-preview1-002111-00"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.0-preview2-25407-01", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.0-preview2-25407-01"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.0"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.3", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.3"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.4", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.4"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.5", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.5"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.6", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.6"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.7", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.7"])
    targeting_pack(name = "microsoft.netcore.app.v2.0.9", packs = ["@dotnet.packs//microsoft.netcore.app.v2.0.9"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.0-preview1-26216-03", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.0-preview1-26216-03"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.0-preview2-26406-04", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.0-preview2-26406-04"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.0-rc1", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.0-rc1"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.0", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.0"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.1", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.1"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.2", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.2"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.3", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.3"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.4", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.4"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.5", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.5"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.6", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.6"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.7", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.7"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.8", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.8"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.9", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.9"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.10", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.10"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.11", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.11"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.12", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.12"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.13", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.13"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.14", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.14"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.15", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.15"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.16", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.16"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.17", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.17"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.18", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.18"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.19", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.19"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.20", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.20"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.21", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.21"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.22", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.22"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.23", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.23"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.24", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.24"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.25", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.25"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.26", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.26"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.27", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.27"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.28", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.28"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.29", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.29"])
    targeting_pack(name = "microsoft.netcore.app.v2.1.30", packs = ["@dotnet.packs//microsoft.netcore.app.v2.1.30"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.0-preview-26820-02", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.0-preview-26820-02"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.0-preview2-26905-02", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.0-preview2-26905-02"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.0-preview3-27014-02", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.0-preview3-27014-02"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.0", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.0"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.1", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.1"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.2", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.2"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.3", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.3"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.4", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.4"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.5", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.5"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.6", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.6"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.7", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.7"])
    targeting_pack(name = "microsoft.netcore.app.v2.2.8", packs = ["@dotnet.packs//microsoft.netcore.app.v2.2.8"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview-27122-01", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview-27122-01"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview-27324-5", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview-27324-5"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview3-27503-5", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview3-27503-5"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview4-27615-11", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview4-27615-11"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview5-27626-15", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview5-27626-15"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview6-27804-01", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview6-27804-01"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview7-27912-14", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview7-27912-14"])
    targeting_pack(name = "microsoft.netcore.app.v3.0.0-preview8-28405-07", packs = ["@dotnet.packs//microsoft.netcore.app.v3.0.0-preview8-28405-07"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.0-preview1-final", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.0-preview1-final"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.0-preview2-final", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.0-preview2-final"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.0-rc1-final", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.0-rc1-final"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.1", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.1"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.5", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.5"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.7", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.7"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.9", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.9"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.10", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.10"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.11", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.11"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.12", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.12"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.13", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.13"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.14", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.14"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.15", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.15"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.16", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.16"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.17", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.17"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.18", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.18"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.19", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.19"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.20", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.20"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.21", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.21"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.22", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.22"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.23", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.23"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.24", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.24"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.25", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.25"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.26", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.26"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.27", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.27"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.28", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.28"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.29", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.29"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.30", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.30"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.31", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.31"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.1.34", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.1.34"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.0-preview1-35029", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.0-preview1-35029"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.0-preview2-35157", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.0-preview2-35157"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.0-preview3-35497", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.0-preview3-35497"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.1", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.1"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.5", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.5"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.7", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.7"])
    targeting_pack(name = "microsoft.aspnetcore.app.v2.2.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v2.2.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.v3.0.0-preview-18579-0056", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v3.0.0-preview-18579-0056"])
    targeting_pack(name = "microsoft.aspnetcore.app.v3.0.0-preview-19075-0444", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v3.0.0-preview-19075-0444"])
    targeting_pack(name = "microsoft.aspnetcore.app.v3.0.0-preview3-19153-02", packs = ["@dotnet.packs//microsoft.aspnetcore.app.v3.0.0-preview3-19153-02"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview3-27503-5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview3-27503-5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview4-27615-11", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview4-27615-11"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview5-27626-15", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview5-27626-15"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview6-27804-01", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview6-27804-01"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview7-27912-14", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview7-27912-14"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview8-28405-07", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview8-28405-07"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-preview9-19423-09", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview9-19423-09"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0-rc1-19456-20", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-rc1-19456-20"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.0"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.0.1", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.0.1"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.1.0-preview1.19506.1", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.1.0-preview1.19506.1"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.1.0-preview2.19525.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.1.0-preview2.19525.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.1.0-preview3.19553.2", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.1.0-preview3.19553.2"])
    targeting_pack(name = "microsoft.netcore.app.ref.v3.1.0", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v3.1.0"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.1.20120.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.1.20120.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.2.20160.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.2.20160.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.3.20214.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.3.20214.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.4.20251.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.4.20251.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.5.20278.1", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.5.20278.1"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.6.20305.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.6.20305.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.7.20364.11", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.7.20364.11"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-preview.8.20407.11", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.8.20407.11"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-rc.1.20451.14", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-rc.1.20451.14"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0-rc.2.20475.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-rc.2.20475.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v5.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v5.0.0"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.1.21102.12", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.1.21102.12"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.2.21154.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.2.21154.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.3.21201.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.3.21201.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.4.21253.7", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.4.21253.7"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.5.21301.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.5.21301.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.6.21352.12", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.6.21352.12"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-preview.7.21377.19", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.7.21377.19"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-rc.1.21451.13", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-rc.1.21451.13"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0-rc.2.21480.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-rc.2.21480.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.0"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.1", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.1"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.2-mauipre.1.22054.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.2-mauipre.1.22054.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.2-mauipre.1.22102.15", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.2-mauipre.1.22102.15"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.2", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.2"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.3", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.3"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.7", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.7"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.9", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.9"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.10", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.10"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.11", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.11"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.12", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.12"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.13", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.13"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.14", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.14"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.15", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.15"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.16", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.16"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.18", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.18"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.19", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.19"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.20", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.20"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.21", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.21"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.22", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.22"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.23", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.23"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.24", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.24"])
    targeting_pack(name = "microsoft.netcore.app.ref.v6.0.25", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v6.0.25"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.1.22076.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.1.22076.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.2.22152.2", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.2.22152.2"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.3.22175.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.3.22175.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.4.22229.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.4.22229.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.5.22301.12", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.5.22301.12"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.6.22324.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.6.22324.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-preview.7.22375.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.7.22375.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-rc.1.22426.10", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-rc.1.22426.10"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0-rc.2.22472.3", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-rc.2.22472.3"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.0"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.1", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.1"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.2", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.2"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.3", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.3"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.7", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.7"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.9", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.9"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.10", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.10"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.11", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.11"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.12", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.12"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.13", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.13"])
    targeting_pack(name = "microsoft.netcore.app.ref.v7.0.14", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v7.0.14"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.1.23110.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.1.23110.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.2.23128.3", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.2.23128.3"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.3.23174.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.3.23174.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.4.23259.5", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.4.23259.5"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.5.23280.8", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.5.23280.8"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.6.23329.7", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.6.23329.7"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-preview.7.23375.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.7.23375.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-rc.1.23419.4", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-rc.1.23419.4"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0-rc.2.23479.6", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-rc.2.23479.6"])
    targeting_pack(name = "microsoft.netcore.app.ref.v8.0.0", packs = ["@dotnet.packs//microsoft.netcore.app.ref.v8.0.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview3-19153-02", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview3-19153-02", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview3-19153-02"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview4-19216-03", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview4-19216-03", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview4-19216-03"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview5-19227-01", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview5-19227-01", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview5-19227-01"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview6.19307.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview6.19307.2", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview6.19307.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview7.19365.7", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview7.19365.7", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview7.19365.7"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview8.19405.7", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview8.19405.7", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview8.19405.7"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-preview9.19424.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-preview9.19424.4", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-preview9.19424.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0-rc1.19457.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0-rc1.19457.4", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0-rc1.19457.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.0", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.0.1", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.0.1", "@dotnet.packs//microsoft.netcore.app.ref.v3.0.1"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.0-preview1.19508.20", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.0-preview1.19508.20", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.0-preview1.19508.20"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.0-preview2.19528.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.0-preview2.19528.8", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.0-preview2.19528.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.0-preview3.19555.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.0-preview3.19555.2", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.0-preview3.19555.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.0", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.2", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.3", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.8", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v3.1.10", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v3.1.10", "@dotnet.packs//microsoft.netcore.app.ref.v3.1.10"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.1.20124.5", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.1.20124.5", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.1.20124.5"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.2.20167.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.2.20167.3", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.2.20167.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.3.20215.14", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.3.20215.14", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.3.20215.14"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.4.20257.10", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.4.20257.10", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.4.20257.10"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.5.20279.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.5.20279.2", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.5.20279.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.6.20312.15", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.6.20312.15", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.6.20312.15"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.7.20365.19", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.7.20365.19", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.7.20365.19"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-preview.8.20414.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-preview.8.20414.8", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-preview.8.20414.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-rc.1.20451.17", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-rc.1.20451.17", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-rc.1.20451.17"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0-rc.2.20475.17", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0-rc.2.20475.17", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0-rc.2.20475.17"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v5.0.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v5.0.0", "@dotnet.packs//microsoft.netcore.app.ref.v5.0.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.1.21103.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.1.21103.6", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.1.21103.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.2.21154.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.2.21154.6", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.2.21154.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.3.21201.13", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.3.21201.13", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.3.21201.13"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.4.21253.5", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.4.21253.5", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.4.21253.5"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.5.21301.17", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.5.21301.17", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.5.21301.17"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.6.21355.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.6.21355.2", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.6.21355.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-preview.7.21378.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-preview.7.21378.6", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-preview.7.21378.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-rc.1.21452.15", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-rc.1.21452.15", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-rc.1.21452.15"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0-rc.2.21480.10", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0-rc.2.21480.10", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0-rc.2.21480.10"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.0", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.2", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.3", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.4", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.5", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.5", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.5"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.6", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.7", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.7", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.7"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.8", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.9", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.9", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.9"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.10", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.10", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.10"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.11", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.11", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.11"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.12", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.12", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.12"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.13", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.13", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.13"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.14", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.14", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.14"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.15", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.15", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.15"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.16", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.16", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.16"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.18", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.18", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.18"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.19", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.19", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.19"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.20", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.20", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.20"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.21", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.21", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.21"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.22", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.22", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.22"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.23", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.23", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.23"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.24", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.24", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.24"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v6.0.25", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v6.0.25", "@dotnet.packs//microsoft.netcore.app.ref.v6.0.25"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.1.22109.13", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.1.22109.13", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.1.22109.13"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.2.22153.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.2.22153.2", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.2.22153.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.3.22178.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.3.22178.4", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.3.22178.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.4.22251.1", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.4.22251.1", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.4.22251.1"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.5.22303.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.5.22303.8", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.5.22303.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.6.22330.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.6.22330.3", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.6.22330.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-preview.7.22376.6", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-preview.7.22376.6", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-preview.7.22376.6"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-rc.1.22427.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-rc.1.22427.2", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-rc.1.22427.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0-rc.2.22476.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0-rc.2.22476.2", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0-rc.2.22476.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.0", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.0"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.1", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.1", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.1"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.2", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.3", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.3", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.3"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.4", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.5", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.5", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.5"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.7", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.7", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.7"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.8", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.9", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.9", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.9"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.10", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.10", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.10"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.11", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.11", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.11"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.12", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.12", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.12"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.13", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.13", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.13"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v7.0.14", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v7.0.14", "@dotnet.packs//microsoft.netcore.app.ref.v7.0.14"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.1.23112.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.1.23112.2", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.1.23112.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.2.23153.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.2.23153.2", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.2.23153.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.3.23177.8", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.3.23177.8", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.3.23177.8"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.4.23260.4", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.4.23260.4", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.4.23260.4"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.5.23302.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.5.23302.2", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.5.23302.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.6.23329.11", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.6.23329.11", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.6.23329.11"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-preview.7.23375.9", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-preview.7.23375.9", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-preview.7.23375.9"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-rc.1.23421.29", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-rc.1.23421.29", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-rc.1.23421.29"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0-rc.2.23480.2", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0-rc.2.23480.2", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0-rc.2.23480.2"])
    targeting_pack(name = "microsoft.aspnetcore.app.ref.v8.0.0", packs = ["@dotnet.packs//microsoft.aspnetcore.app.ref.v8.0.0", "@dotnet.packs//microsoft.netcore.app.ref.v8.0.0"])

