"""Framework tables read from the .NET SDK.

GENERATED BY SDK GENERATOR -- see dotnet/private/sdk/gen.

The framework lists mirror the Supported*TargetFramework item groups in
Microsoft.NET.SupportedTargetFrameworks.props, which is what the SDK's
GenerateNETCompatibleDefineConstants target consumes. A framework absent
from these lists never gets an *_OR_GREATER symbol.

SDK_LANG_VERSIONS maps each framework to the C# language version the SDK
defaults to for it. Newer language features depend on runtime support that
older targets lack, which is why the cap exists.

DEFAULT_TARGET_FRAMEWORK is the newest generally-available framework.
Previews and release candidates are excluded: their packs are not
published as stable versions, so every table here stops at the same
release and they cannot drift apart.
"""

# Read from .NET SDK 11.0.100-rc.1.26425.128.

DEFAULT_TARGET_FRAMEWORK = "net10.0"

SDK_NETSTANDARD_FRAMEWORKS = [
    "netstandard1.0",
    "netstandard1.1",
    "netstandard1.2",
    "netstandard1.3",
    "netstandard1.4",
    "netstandard1.5",
    "netstandard1.6",
    "netstandard2.0",
    "netstandard2.1",
]

SDK_NETFRAMEWORK_FRAMEWORKS = [
    "net20",
    "net30",
    "net35",
    "net40",
    "net45",
    "net451",
    "net452",
    "net46",
    "net461",
    "net462",
    "net47",
    "net471",
    "net472",
    "net48",
    "net481",
]

SDK_NETCOREAPP_FRAMEWORKS = [
    "netcoreapp1.0",
    "netcoreapp1.1",
    "netcoreapp2.0",
    "netcoreapp2.1",
    "netcoreapp2.2",
    "netcoreapp3.0",
    "netcoreapp3.1",
    "net5.0",
    "net6.0",
    "net7.0",
    "net8.0",
    "net9.0",
    "net10.0",
]

SDK_LANG_VERSIONS = {
    "netstandard1.0": "7.3",
    "netstandard1.1": "7.3",
    "netstandard1.2": "7.3",
    "netstandard1.3": "7.3",
    "netstandard1.4": "7.3",
    "netstandard1.5": "7.3",
    "netstandard1.6": "7.3",
    "netstandard2.0": "7.3",
    "netstandard2.1": "8.0",
    "net20": "7.3",
    "net30": "7.3",
    "net35": "7.3",
    "net40": "7.3",
    "net45": "7.3",
    "net451": "7.3",
    "net452": "7.3",
    "net46": "7.3",
    "net461": "7.3",
    "net462": "7.3",
    "net47": "7.3",
    "net471": "7.3",
    "net472": "7.3",
    "net48": "7.3",
    "net481": "7.3",
    "netcoreapp1.0": "7.3",
    "netcoreapp1.1": "7.3",
    "netcoreapp2.0": "7.3",
    "netcoreapp2.1": "7.3",
    "netcoreapp2.2": "7.3",
    "netcoreapp3.0": "8.0",
    "netcoreapp3.1": "8.0",
    "net5.0": "9.0",
    "net6.0": "10.0",
    "net7.0": "11.0",
    "net8.0": "12.0",
    "net9.0": "13.0",
    "net10.0": "14.0",
}

# Each framework mapped to the frameworks it can directly compile against.
# The relationship is transitive. Order matters: netstandard first, and
# within a family oldest to newest.
FRAMEWORK_COMPATIBILITY = {
    # .NET Standard
    "netstandard": [],
    "netstandard1.0": ["netstandard"],
    "netstandard1.1": ["netstandard1.0"],
    "netstandard1.2": ["netstandard1.1"],
    "netstandard1.3": ["netstandard1.2"],
    "netstandard1.4": ["netstandard1.3"],
    "netstandard1.5": ["netstandard1.4"],
    "netstandard1.6": ["netstandard1.5"],
    "netstandard2.0": ["netstandard1.6"],
    "netstandard2.1": ["netstandard2.0"],

    # .NET Framework
    "net11": [],
    "net20": ["net11"],
    "net30": ["net20"],
    "net35": ["net30"],
    "net40": ["net35"],
    "net403": ["net40"],
    "net45": ["net403", "netstandard1.1"],
    "net451": ["net45", "netstandard1.2"],
    "net452": ["net451"],
    "net46": ["net452", "netstandard1.3"],
    "net461": ["net46", "netstandard2.0"],
    "net462": ["net461"],
    "net47": ["net462"],
    "net471": ["net47"],
    "net472": ["net471"],
    "net48": ["net472"],
    "net481": ["net48"],

    # .NET Core
    "netcoreapp1.0": ["netstandard1.6"],
    "netcoreapp1.1": ["netcoreapp1.0"],
    "netcoreapp2.0": ["netcoreapp1.1", "netstandard2.0"],
    "netcoreapp2.1": ["netcoreapp2.0"],
    "netcoreapp2.2": ["netcoreapp2.1"],
    "netcoreapp3.0": ["netcoreapp2.2", "netstandard2.1"],
    "netcoreapp3.1": ["netcoreapp3.0"],
    "net5.0": ["netcoreapp3.1"],
    "net6.0": ["net5.0"],
    "net7.0": ["net6.0"],
    "net8.0": ["net7.0"],
    "net9.0": ["net8.0"],
    "net10.0": ["net9.0"],
}
