"""The .NET runtime band that each target framework's packs come from.

GENERATED BY SDK GENERATOR
"""

PACK_BANDS = {
    "netcoreapp1.0": {"ref": "1.0.16"},
    "netcoreapp1.1": {"ref": "1.1.13"},
    "netcoreapp2.0": {"ref": "2.0.9"},
    "netcoreapp2.1": {"ref": "2.1.30", "web_ref": "2.1.34"},
    "netcoreapp2.2": {"ref": "2.2.8", "web_ref": "2.2.8"},
    "netcoreapp3.0": {"ref": "3.0.1", "web_ref": "3.0.1", "runtime": "3.0.3", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-x64", "win-arm64", "win-x64"], "web_rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-x64", "win-x64"]},
    "netcoreapp3.1": {"ref": "3.1.0", "web_ref": "3.1.10", "runtime": "3.1.32", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-x64", "win-arm64", "win-x64"]},
    "net5.0": {"ref": "5.0.0", "web_ref": "5.0.0", "runtime": "5.0.17", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-x64", "win-arm64", "win-x64"]},
    "net6.0": {"ref": "6.0.36", "web_ref": "6.0.36", "runtime": "6.0.36", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64"]},
    "net7.0": {"ref": "7.0.20", "web_ref": "7.0.20", "runtime": "7.0.20", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64"]},
    "net8.0": {"ref": "8.0.31", "web_ref": "8.0.31", "runtime": "8.0.31", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64"]},
    "net9.0": {"ref": "9.0.20", "web_ref": "9.0.20", "runtime": "9.0.20", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64"], "ilcompiler": "9.0.20"},
    "net10.0": {"ref": "10.0.12", "web_ref": "10.0.12", "runtime": "10.0.12", "rids": ["linux-arm64", "linux-musl-arm64", "linux-musl-x64", "linux-x64", "osx-arm64", "osx-x64", "win-arm64", "win-x64"], "ilcompiler": "10.0.12"},
}
