#!/usr/bin/env python3
"""Generate a synthetic rules_dotnet workspace for performance benchmarking.

Libraries are laid out in layers, each depending on several targets from the two
layers below it, so the transitive closures the rules walk are the ones a real
dependency graph produces.

Everything the workspace needs beyond the ruleset is copied out of `examples/`,
so a generated workspace reuses NuGet archives already in the repository cache.
"""

import argparse
import os
import random
import shutil
import sys

# Packages from examples/paket.lock. These pull deep transitive graphs, which is
# the point: they exercise import_library and the per-package select().
NUGET_DEPS = [
    "@paket.example_deps//microsoft.codeanalysis.csharp",
    "@paket.example_deps//microsoft.codeanalysis.common",
    "@paket.example_deps//system.collections.immutable",
    "@paket.example_deps//mono.cecil",
]

MODULE_TEMPLATE = '''"rules_dotnet benchmark workspace (generated by tools/bench/gen_workspace.py)"

module(
    name = "rules_dotnet_bench",
    version = "0.0.0",
    compatibility_level = 1,
)

bazel_dep(name = "rules_dotnet", version = "0.0.0")
local_path_override(
    module_name = "rules_dotnet",
    path = "{rules_path}",
)

dotnet = use_extension("@rules_dotnet//dotnet:extensions.bzl", "dotnet")
dotnet.toolchain(dotnet_version = "{sdk_version}")
use_repo(dotnet, "dotnet_toolchains")

register_toolchains("@dotnet_toolchains//:all")

paket = use_extension("@rules_dotnet//dotnet:paket.bzl", "paket")
paket.parse(
    dependencies = "//:paket.dependencies",
    lock = "//:paket.lock",
)
use_repo(paket, "paket.example_deps")
'''

# The profiling flags are left out; the runner turns them on per invocation.
BAZELRC = '''startup --windows_enable_symlinks
common --enable_runfiles
common --incompatible_strict_action_env
common --test_output=errors

build --@rules_dotnet//dotnet/settings:use_compiler_worker=true

common --enable_platform_specific_config
common:linux --experimental_output_paths=strip
common:macos --experimental_output_paths=strip

# common:, not build:, so `bazel query --config=profile` works too.
common:profile --noslim_profile
common:profile --experimental_profile_include_target_label
common:profile --experimental_profile_include_primary_output

try-import %workspace%/.bazelrc.user
'''


def lib_name(i):
    return "pkg%04d" % i


def namespace(i):
    return "Pkg%04d" % i


def source_file(owner, index, deps):
    """One .cs file. File 0 of a library holds the type its dependents read."""
    lines = ["namespace %s" % namespace(owner), "{"]
    if index == 0:
        lines += [
            "    public static class Type0",
            "    {",
            "        public static int Value => %d;" % (owner % 97 + 1),
            "    }",
        ]
    # A real cross-assembly reference per dep, so an edit actually cascades.
    body = " + ".join("%s.Type0.Value" % namespace(d) for d in deps) or "0"
    lines += [
        "    public static class Type%d" % (index + 1),
        "    {",
        "        public static int Sum() => %s;" % body,
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def program_file(name, deps):
    body = " + ".join("%s.Type0.Value" % namespace(d) for d in deps) or "0"
    return (
        "public static class %s\n"
        "{\n"
        "    public static int Main()\n"
        "    {\n"
        "        System.Console.WriteLine(%s);\n"
        "        return 0;\n"
        "    }\n"
        "}\n" % (name, body)
    )


def write(path, content):
    with open(path, "w") as handle:
        handle.write(content)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="Directory to generate into (wiped first).")
    parser.add_argument("--rules-path", required=True, help="Path to the rules_dotnet checkout to build against.")
    parser.add_argument("--examples", default=None, help="Path to examples/ to copy paket files from. Defaults to <rules-path>/examples.")
    parser.add_argument("--libs", type=int, default=1000)
    parser.add_argument("--srcs", type=int, default=5)
    parser.add_argument("--layers", type=int, default=12)
    parser.add_argument("--deps", type=int, default=4)
    parser.add_argument("--bins", type=int, default=25)
    parser.add_argument("--tests", type=int, default=25)
    parser.add_argument("--nuget", type=int, default=10)
    parser.add_argument("--publish", type=int, default=2)
    parser.add_argument("--tfms", default="net10.0", help="Comma separated. Libraries declare all of them; roots pick one each.")
    parser.add_argument("--sdk-version", default="10.0.201")
    parser.add_argument("--seed", type=int, default=1)
    args = parser.parse_args(argv)

    rng = random.Random(args.seed)
    tfms = [t.strip() for t in args.tfms.split(",") if t.strip()]
    examples = args.examples or os.path.join(args.rules_path, "examples")

    out = os.path.abspath(args.out)
    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(out)

    # Assign libraries to layers, then draw each target's deps from the two
    # layers below it. Two layers rather than one gives diamonds and fan-in.
    layers = [[] for _ in range(max(args.layers, 1))]
    for i in range(args.libs):
        layers[i % len(layers)].append(i)

    deps_of = {}
    for depth, layer in enumerate(layers):
        pool = []
        for below in (depth - 1, depth - 2):
            if below >= 0:
                pool.extend(layers[below])
        for i in layer:
            k = min(args.deps, len(pool))
            deps_of[i] = sorted(rng.sample(pool, k)) if k else []

    nuget_libs = set(rng.sample(range(args.libs), min(args.nuget, args.libs)))
    tfm_literal = ", ".join('"%s"' % t for t in tfms)

    for i in range(args.libs):
        pkg = lib_name(i)
        os.makedirs(os.path.join(out, pkg))
        srcs = []
        for s in range(args.srcs):
            filename = "Src%d.cs" % s
            write(os.path.join(out, pkg, filename), source_file(i, s, deps_of[i]))
            srcs.append(filename)

        labels = ['"//%s"' % lib_name(d) for d in deps_of[i]]
        if i in nuget_libs:
            labels += ['"%s"' % d for d in NUGET_DEPS[: 1 + (i % len(NUGET_DEPS))]]

        write(
            os.path.join(out, pkg, "BUILD.bazel"),
            'load("@rules_dotnet//dotnet:defs.bzl", "csharp_library")\n\n'
            "csharp_library(\n"
            '    name = "%s",\n'
            "    srcs = [%s],\n"
            "    target_frameworks = [%s],\n"
            "    visibility = [\"//visibility:public\"],\n"
            "    deps = [%s],\n"
            ")\n"
            % (
                pkg,
                ", ".join('"%s"' % s for s in srcs),
                tfm_literal,
                ", ".join(labels),
            ),
        )

    # Roots sit on top of the last two layers, so a root pulls in a deep closure.
    root_pool = [i for depth in (len(layers) - 1, len(layers) - 2) if depth >= 0 for i in layers[depth]]
    roots = []

    def root_deps():
        k = min(args.deps, len(root_pool))
        return sorted(rng.sample(root_pool, k)) if k else []

    for b in range(args.bins):
        name = "bin%03d" % b
        deps = root_deps()
        os.makedirs(os.path.join(out, name))
        write(os.path.join(out, name, "Program.cs"), program_file("Program", deps))
        write(
            os.path.join(out, name, "BUILD.bazel"),
            'load("@rules_dotnet//dotnet:defs.bzl", "csharp_binary")\n\n'
            "csharp_binary(\n"
            '    name = "%s",\n'
            '    srcs = ["Program.cs"],\n'
            '    target_frameworks = ["%s"],\n'
            "    visibility = [\"//visibility:public\"],\n"
            "    deps = [%s],\n"
            ")\n"
            % (name, tfms[b % len(tfms)], ", ".join('"//%s"' % lib_name(d) for d in deps)),
        )
        roots.append((name, tfms[b % len(tfms)]))

    for t in range(args.tests):
        name = "test%03d" % t
        deps = root_deps()
        os.makedirs(os.path.join(out, name))
        write(os.path.join(out, name, "Program.cs"), program_file("Program", deps))
        write(
            os.path.join(out, name, "BUILD.bazel"),
            'load("@rules_dotnet//dotnet:defs.bzl", "csharp_test")\n\n'
            "csharp_test(\n"
            '    name = "%s",\n'
            '    srcs = ["Program.cs"],\n'
            '    target_frameworks = ["%s"],\n'
            "    deps = [%s],\n"
            ")\n"
            % (name, tfms[t % len(tfms)], ", ".join('"//%s"' % lib_name(d) for d in deps)),
        )

    # A publish must target the framework its binary was built for.
    for p in range(min(args.publish, len(roots))):
        (binary_name, binary_tfm) = roots[p]
        name = "publish%03d" % p
        os.makedirs(os.path.join(out, name))
        write(
            os.path.join(out, name, "BUILD.bazel"),
            'load("@rules_dotnet//dotnet:defs.bzl", "publish_binary")\n\n'
            "publish_binary(\n"
            '    name = "%s",\n'
            '    binary = "//%s",\n'
            "    self_contained = %s,\n"
            '    target_framework = "%s",\n'
            ")\n"
            % (name, binary_name, "True" if p % 2 == 0 else "False", binary_tfm),
        )

    write(os.path.join(out, "MODULE.bazel"), MODULE_TEMPLATE.format(
        rules_path=os.path.abspath(args.rules_path), sdk_version=args.sdk_version))
    write(os.path.join(out, ".bazelrc"), BAZELRC)
    write(os.path.join(out, "BUILD.bazel"), "")
    for name in ("paket.dependencies", "paket.lock"):
        shutil.copyfile(os.path.join(examples, name), os.path.join(out, name))
    shutil.copyfile(os.path.join(args.rules_path, ".bazelversion"), os.path.join(out, ".bazelversion"))

    total = args.libs + args.bins + args.tests + min(args.publish, len(roots))
    edges = sum(len(d) for d in deps_of.values()) + (args.bins + args.tests) * min(args.deps, len(root_pool))
    print("generated %s" % out)
    print("  targets: %d (%d libs, %d bins, %d tests, %d publish)"
          % (total, args.libs, args.bins, args.tests, min(args.publish, len(roots))))
    print("  dep edges: %d   layers: %d   tfms: %s" % (edges, len(layers), ",".join(tfms)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
