"""Tests for reading the metadata files that ship inside a `.nupkg`."""

load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load(
    "//dotnet/private:common.bzl",
    "get_nearest_compatible_target_framework",
    "nuget_framework_to_tfm",
)
load("//dotnet/private:xml.bzl", "xml")
load("//dotnet/private/rules/nuget:package.bzl", "deps_by_tfm")
load(
    "//dotnet/private/rules/nuget:package_metadata.bzl",
    "parse_dotnet_tool_settings",
    "parse_framework_list",
    "parse_nuspec",
    "parse_package_overrides",
)

_NUSPEC = """\
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="2.12">
    <id>NUnitLite</id>
    <version>3.14.0</version>
    <description>Supported platforms:
- .NET Framework 3.5+ &amp; later</description>
    <!-- A comment mentioning <dependency id="NotReal" /> -->
    <!-- <![CDATA[ and a CDATA section holding <dependency id="AlsoNotReal" /> ]]> -->
    <dependencies>
      <group targetFramework=".NETFramework3.5">
        <dependency id="NUnit" version="[3.14.0]" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="NUnit" version="[3.14.0]" />
        <dependency id="NETStandard.Library" version="2.0.0" />
      </group>
      <group targetFramework=".NETCoreApp3.1">
        <dependency id="NUnit" version="[3.14.0]" />
      </group>
      <group targetFramework="net7.0">
        <dependency id="NUnit" version="[3.14.0]" />
      </group>
      <group targetFramework="MonoAndroid10" />
    </dependencies>
  </metadata>
</package>
"""

_TOOL_NUSPEC = """\
<?xml version="1.0" encoding="utf-8"?>
<package>
  <metadata>
    <id>CSharpier</id>
    <packageTypes>
      <packageType name="DotnetTool" />
    </packageTypes>
  </metadata>
</package>
"""

_LEGACY_NUSPEC = """\
<package>
  <metadata>
    <id>Legacy</id>
    <dependencies>
      <dependency id="NUnit" version="3.0.0" />
    </dependencies>
  </metadata>
</package>
"""

_FRAMEWORK_LIST = """\
<FileList TargetFrameworkIdentifier=".NETCoreApp" FrameworkName="Microsoft.NETCore.App">
  <File Type="Analyzer" Path="analyzers/dotnet/cs/Gen.dll" AssemblyName="Gen" AssemblyVersion="6.0.6.21309" />
  <File Type="Managed" Path="ref/net6.0/Microsoft.CSharp.dll" AssemblyName="Microsoft.CSharp" AssemblyVersion="6.0.0.0" />
  <File Type="Managed" Path="ref/net6.0/System.Xml.dll" AssemblyName="System.Xml" AssemblyVersion="4.0.0.0" />
</FileList>
"""

_PACKAGE_OVERRIDES = """\
Microsoft.CSharp|4.4.0
Microsoft.Win32.Primitives|4.3.0

"""

_TOOL_SETTINGS = """\
<?xml version="1.0" encoding="utf-8"?>
<DotNetCliTool Version="1">
  <Commands>
    <Command Name="csharpier" EntryPoint="CSharpier.dll" Runner="dotnet" />
  </Commands>
</DotNetCliTool>
"""

# The dependencies NUnitLite 3.14.0 resolves to for every framework, as
# generated by the paket2bazel tool this replaced.
_NUNITLITE_DEPS = {
    "net10.0": ["NUnit"],
    "net11": [],
    "net20": [],
    "net30": [],
    "net35": ["NUnit"],
    "net40": ["NUnit"],
    "net403": ["NUnit"],
    "net45": ["NUnit"],
    "net451": ["NUnit"],
    "net452": ["NUnit"],
    "net46": ["NUnit"],
    "net461": ["NUnit"],
    "net462": ["NUnit"],
    "net47": ["NUnit"],
    "net471": ["NUnit"],
    "net472": ["NUnit"],
    "net48": ["NUnit"],
    "net481": ["NUnit"],
    "net5.0": ["NUnit"],
    "net6.0": ["NUnit"],
    "net7.0": ["NUnit"],
    "net8.0": ["NUnit"],
    "net9.0": ["NUnit"],
    "netcoreapp1.0": [],
    "netcoreapp1.1": [],
    "netcoreapp2.0": ["NUnit", "NETStandard.Library"],
    "netcoreapp2.1": ["NUnit", "NETStandard.Library"],
    "netcoreapp2.2": ["NUnit", "NETStandard.Library"],
    "netcoreapp3.0": ["NUnit", "NETStandard.Library"],
    "netcoreapp3.1": ["NUnit"],
    "netstandard": [],
    "netstandard1.0": [],
    "netstandard1.1": [],
    "netstandard1.2": [],
    "netstandard1.3": [],
    "netstandard1.4": [],
    "netstandard1.5": [],
    "netstandard1.6": [],
    "netstandard2.0": ["NUnit", "NETStandard.Library"],
    "netstandard2.1": ["NUnit", "NETStandard.Library"],
}

_TFMS = {
    ".NETStandard2.0": "netstandard2.0",
    ".NETStandard1.6": "netstandard1.6",
    ".NETFramework4.7.2": "net472",
    ".NETFramework4.5": "net45",
    ".NETFramework4.0.3": "net403",
    ".NETFramework,Version=v4.6.1": "net461",
    ".NETCoreApp3.1": "netcoreapp3.1",
    ".NETCoreApp5.0": "net5.0",
    ".NETCoreApp10.0": "net10.0",
    "net472": "net472",
    "net9.0": "net9.0",
    "netstandard": "netstandard",
    "MonoAndroid10": None,
    "Xamarin.iOS10": None,
    ".NETPortable0.0-Profile259": None,
    ".NETFramework0.0": None,
    "uap10.0": None,
    "": None,
}

def _xml_test_impl(ctx):
    env = unittest.begin(ctx)
    package = xml.parse(_NUSPEC)
    metadata = xml.child(package, "metadata")

    asserts.equals(env, "package", xml.local_name(package))
    asserts.equals(env, "2.12", xml.attr(metadata, "minClientVersion"))
    asserts.equals(env, "", xml.attr(metadata, "nope"))
    asserts.equals(
        env,
        5,
        len(xml.children(xml.child(metadata, "dependencies"), "group")),
        "elements inside a comment or a CDATA section are not elements",
    )

    return unittest.end(env)

_xml_test = unittest.make(_xml_test_impl)

def _parse_nuspec_test_impl(ctx):
    env = unittest.begin(ctx)
    nuspec = parse_nuspec(_NUSPEC)

    asserts.false(env, nuspec.is_dotnet_tool)
    asserts.equals(
        env,
        {
            "net35": ["NUnit"],
            "net7.0": ["NUnit"],
            "netcoreapp3.1": ["NUnit"],
            "netstandard2.0": ["NUnit", "NETStandard.Library"],
        },
        nuspec.dependency_groups,
        "groups for unsupported frameworks are dropped",
    )

    asserts.true(env, parse_nuspec(_TOOL_NUSPEC).is_dotnet_tool)
    asserts.equals(
        env,
        {"": ["NUnit"]},
        parse_nuspec(_LEGACY_NUSPEC).dependency_groups,
        "dependencies outside a group apply to every framework",
    )

    return unittest.end(env)

_parse_nuspec_test = unittest.make(_parse_nuspec_test_impl)

def _deps_by_tfm_test_impl(ctx):
    env = unittest.begin(ctx)
    packages = {"netstandard.library": "netstandard.library", "nunit": "nunit"}

    actual = deps_by_tfm(parse_nuspec(_NUSPEC).dependency_groups, packages)

    asserts.equals(
        env,
        {
            "@rules_dotnet//dotnet:tfm_{}".format(tfm): [
                "//{}".format(id.lower())
                for id in ids
            ]
            for (tfm, ids) in _NUNITLITE_DEPS.items()
        },
        {
            condition: labels
            for (condition, labels) in actual.items()
            if condition != "//conditions:default"
        },
    )

    asserts.equals(
        env,
        {},
        {
            condition: labels
            for (condition, labels) in deps_by_tfm(
                parse_nuspec(_NUSPEC).dependency_groups,
                {},
            ).items()
            if labels
        },
        "dependencies that the group did not resolve are dropped",
    )

    return unittest.end(env)

_deps_by_tfm_test = unittest.make(_deps_by_tfm_test_impl)

def _framework_test_impl(ctx):
    env = unittest.begin(ctx)

    for (framework, expected) in _TFMS.items():
        asserts.equals(env, expected, nuget_framework_to_tfm(framework), framework)

    asserts.equals(
        env,
        "net45",
        get_nearest_compatible_target_framework("net48", ["netstandard2.0", "net45"]),
        "a framework of the same family wins over a compatible one",
    )
    asserts.equals(
        env,
        "netstandard2.0",
        get_nearest_compatible_target_framework("net10.0", ["netstandard2.0", "net48"]),
        ".NET Framework is not compatible with .NET",
    )
    asserts.equals(
        env,
        None,
        get_nearest_compatible_target_framework("net20", ["netstandard2.0"]),
    )

    return unittest.end(env)

_framework_test = unittest.make(_framework_test_impl)

def _package_files_test_impl(ctx):
    env = unittest.begin(ctx)

    asserts.equals(
        env,
        {"microsoft.csharp": "6.0.0.0", "system.xml": "4.0.0.0"},
        parse_framework_list(_FRAMEWORK_LIST),
        "only managed assemblies are part of the framework list",
    )
    asserts.equals(
        env,
        {"microsoft.csharp": "4.4.0", "microsoft.win32.primitives": "4.3.0"},
        parse_package_overrides(_PACKAGE_OVERRIDES),
    )
    asserts.equals(
        env,
        [{"entrypoint": "CSharpier.dll", "name": "csharpier", "runner": "dotnet"}],
        parse_dotnet_tool_settings(_TOOL_SETTINGS, "DotnetToolSettings.xml"),
    )

    return unittest.end(env)

_package_files_test = unittest.make(_package_files_test_impl)

def package_metadata_test_suite(name):
    unittest.suite(
        name,
        _deps_by_tfm_test,
        _framework_test,
        _package_files_test,
        _parse_nuspec_test,
        _xml_test,
    )
