load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_xunit_test")

#core_xunit_test(
#    name = "example_xunit",
#    srcs = [
#        "MyTest.cs",
#    ],
#    deps = [
#        "@xunit.extensibility.core//:core",
#        "@xunit.assert//:core",
#    ],
#    size = "small",
#)
