workspace(
    name = "examples",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "c6966ec828da198c5d9adbaa94c05e3a1c7f21bd012a0b29ba8ddbccb2c93b0d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz",
    ],
)

local_repository(
    name = "rules_dotnet",
    path = "..",
)

load(
    "@rules_dotnet//dotnet:repositories.bzl",
    "dotnet_register_toolchains",
    "rules_dotnet_dependencies",
)

load("@rules_dotnet//dotnet/private:rules/nuget_repo.bzl", "nuget_repo")

nuget_repo(
    name = "nuget",
    packages = [
        ("Microsoft.NETCore.App.Ref", "5.0.0", "sha512-bBp1LYzTBY58dMaCABHnp44CYBcBvW7RrfSsXENaS7iRq/yx39g+jhWdgUBZcJQBoF6AZeGbHhKV+JAoT3LHDw==", []),
        ("Microsoft.NETCore.App.Ref", "6.0.0", "sha512-YlT7r1FYRY8MysjHx7783xRMpUbstl0WWub4xiyAd16qjL2oN5al7MEJE+u8NI7YWSXKZtNGg8agbLu1cr9pHg==", []),
        # ("System.Text.Encodings.Web", "5.0.1", "sha512-OIgt7MMK++wCxGYX4CFnYrF59Xj+CSdGGFLCey204hr/9nBlW1uwfkFOrPbvh/BkOHy85zyHaP+trTO4mY0thA==", []),
    ]
)

rules_dotnet_dependencies()

dotnet_register_toolchains("dotnet", "6.0.300")
