load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load(":runtime_pack.bzl", "runtime_pack")

label_setting(
    name = "runtime_pack",
    build_setting_default = ":empty_pack",
    visibility = ["//visibility:public"],
)

# This target is only for the default value of the label setting
# and the transition should always transition from it to something else
runtime_pack(
    name = "empty_pack",
    packs = [],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "runtime_pack_transition",
    srcs = ["runtime_pack_transition.bzl"],
    visibility = ["//dotnet:__subpackages__"],
    deps = [
        "//dotnet/private:providers",
        "//dotnet/private/sdk:packs",
    ],
)
