load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load(
    "//dotnet:defs.bzl",
    "publish_binary",
)

publish_binary(
    name = "ready2run",
    binary = "//dotnet/private/tests/publish/app_to_publish",
    ready_to_run = True,
    self_contained = True,
    target_framework = "net10.0",
)

# We tar the output to because that way we can strip the
# prefix of the files and avoid long path issues on Windows.
# This also makes sure that it's possible to tar the output
# of the publish without any problems
pkg_tar(
    name = "tar",
    srcs = [":ready2run"],
    include_runfiles = True,
    mode = "0755",
    package_dir = "/",
    strip_prefix = select(
        {
            "//dotnet/private:linux-x64": "ready2run/publish/linux-x64",
            "//dotnet/private:linux-arm64": "ready2run/publish/linux-arm64",
            "//dotnet/private:osx-x64": "ready2run/publish/osx-x64",
            "//dotnet/private:osx-arm64": "ready2run/publish/osx-arm64",
            "//dotnet/private:windows-x64": "ready2run/publish/win-x64",
            "//dotnet/private:windows-arm64": "ready2run/publish/win-arm64",
        },
    ),
)

sh_test(
    name = "ready2run_test",
    srcs = [
        "test.sh",
    ],
    data = [":tar"],
)
